[package]
name = "aptly-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Plugin interfaces and extension points for aptly-cli"
repository = "https://github.com/0xbe1/aptly"

[dependencies]
anyhow.workspace = true
serde.workspace = true
